### ISSUE TITLE
Direktnachrichten

### ISSUE THREAD

**Issue by danielmoessner** [lawandorga/lawandorga-backend-service#79]
# Problem

`The best problem definition consists of a single specific story that shows why the status quo doesn’t work.`

Aktuell vernetzen sich Studenten der Law Clinic über Nachrichtentools wie WhatsApp, Signal, Slack oder ähnliche. Das ist datenschutzrechtlich keine gute Lösung für sensible Daten und eine schlechte Auftrennung bzgl. privater und "geschäftlicher" Kommunikation. Zusätzlich dient es als Nutzerbindung.

# Appetite

`How much time should be spent on this project?`

6 Wochen

# Solution

`How will the problem be solved? Add embedded and fat marker sketches.`

Nutzer sollen sich Direktnachrichten senden können. Entweder zu sich selbst, zu einem anderen Nutzer oder zu mehreren Nutzern.

## Requirements

- Nur 1 Login nötig also automatische Anmeldung
- Alle Daten bleiben auf Servern von Law&Orga
- Navigationsleiste muss stehen bleiben auf der linken Seite
- Encryption muss gewährleistet sein
- Es dürfen keine externen Kosten entstehen

## Optional Features

- Kommentieren auf Nachrichten genauso wie in Slack
- Nachrichten aktualisieren automatisch bei offenem Fenster
- Automatisches Übergeben von Keys, nachdem sie verloren gegangen sind
- Fixieren von Chats

## Technical

- Chat: Created, Updated, Name, Users
- Message: Created, Updated, User, Message 
- ChatEncryption: User, Chat, Key, Correct

## Todos

- [ ] Matrix Docker Container für Synapse (GitHub Repo mit Config und Pipeline)
- [ ] Frontend: Links Navigations Link "Chats"
- [ ] Kommunikation zu anderen Matrix Servern kappen
- [ ] Handy Login langfristig möglich
- [ ] Sprach- und Videoanrufe deaktivieren

Wenn Element:
- [ ] Bestehender Frontend Client über iframe (Element)
- [ ] Frontend: Automatisches Login
- [ ] Backend: OpenID

Wenn JavaScript:
- [ ] Frontend: Chat Funktion komplett selber bauen

# Rabbit holes

`What could go wrong? Or what problems might come up?`

- Im Nachhinein Personen zum Chat hinzufügen
- Person vergisst ihr Passwort und verliert dadurch ihre Keys
- Rich Text Message

# No-gos

`What will not be done?`

- File Upload in Chats

**Comment by danielmoessner** [comment]
anhang zum problem: bindung an law and orga

**Comment by danielmoessner** [comment]
einbinden muss funktionieren:
- nur 1 login (automatische anmeldung)
- alles bei uns daten
- navigationsleiste links muss dableiben
- encryption
- kein externer service
