### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by danielmoessner** [lawandorga/lawandorga-backend-service#80]
# Problem

`The best problem definition consists of a single specific story that shows why the status quo doesn’t work.`

Law Clinics managen ihre internen Events über eigene aufgebaute Kalender. Das ist technisch aufwending und von der Synchronisation nicht angenehm für alle Nutzer. Außerdem haben die Law Clinics aktuell keine gute Möglichkeit sich bezüglich Events miteinander zu vernetzen.

# Appetite

`How much time should be spent on this project?`

4 Wochen

# Solution

`How will the problem be solved? Add embedded and fat marker sketches.`

Events sollen in einem Kalender eingetragen werden können. Events können entweder auf Organisationsebene oder auf globaler Ebene sein.

## Technical

- Event: Law Clinic, Created, Updated, Level, Name, Start DateTime, End DateTime, Description

## Optional Features

- Verknüpfung mit persönlichem Kalender
- Ansicht wie in Basecamp
- Termine in den Records selber für Statistik

## Todos

- [x] Frontend: Links Reiter für Events
- [x] Frontend: Liste an Events
- [x] Frontend: Anlegen, Bearbeiten und Löschen von Events
- [x] Backend: Events CRUD
- [x] Synchronisation mit eigenem persönlichen Kalender über URL oder ähnlichem

# Rabbit holes

`What could go wrong? Or what problems might come up?`

- Verknüpfung mit persönlichem Kalender

# No-gos

`What will not be done?`

- Privater Kalender

**Comment by danielmoessner** [comment]
andere personen einladen zu dem event

**Comment by danielmoessner** [comment]
highlight funktion der events

**Comment by danielmoessner** [comment]
zusagen funktion

**Comment by danielmoessner** [comment]
Notiz an mich selber sobald fertig: Im Mailverkehr nachsehen für das Datum Mi., 14. Sept., 22:07 um Feedback einzuholen von einer Person, die das Feature requested hatte.

**Comment by Zarrck** [comment]
Visuelle Trennung von globalen und lokalen Events
   Farbiger Streifen oben an der Eventkarte
      Law&Orga Blau für lokale Events
      Grau für globale Events

Kalender Abo Funktion trennen nach globalen und lokalen Events
   Schnelle Lösung: Jeweils ein eigener Link für globale und lokale Events
   Saubere Lösung: Checkbox "Include Global Events" & "Include Local Events" und ein Link mit entsprechendem Inhalt
