### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by danielmoessner** [lawandorga/lawandorga-backend-service#81]
# Problem

`The best problem definition consists of a single specific story that shows why the status quo doesn’t work.`

Die meisten Law Clinics benutzen eigene Mail Server oder Mail Server von Domain-Anbietern. Oft ist die Einrichtung kompliziert und oder der Datenschutz nicht gewährleistet. Niemand sollte sich mit technischen Fragen rumquälen müssen, wenn er an sich nur seiner Beratung nachgehen will. Zudem ist es umständlich alle Mitglieder der Law Clinic doppelt managen zu müssen, einmal beim Mail-Anbieter und einmal bei Law&Orga.

# Appetite

`How much time should be spent on this project?`

6 Wochen

# Solution

`How will the problem be solved? Add embedded and fat marker sketches.`

Wir betreiben eigene Mail-Server die automatisch nach Bedarf hochgefahren werden. Im Law&Orga Admin Bereich kann einmal global die Mail eingerichtet werden und daraufhin E-Mail Adressen hinzugefügt. Die Verbindung zu diesen Mails läuft über IMAP und SMTP. Das Passwort soll in Law&Orga geändert werden können.

## Required

- Jede Person eine Mail (automatisch mit vorname.nachname.zahl@) sobald MX Records angelegt
- Backups

## Good

- Shared Postfach
- Internet Mail Client

## Optional

- Alias

## Todos

- [x] Frontend: Admin Bereich für MX Records (X Schritte für jeden DNS Eintrag)
- [x] Frontend: Anzeigen der SMTP und IMAP Einstellungen für jeden User in seinem Profil mit Passwort
- [x] Frontend: Anzeigen der Law&Orga E-Mail von jedem User
- [x] Backend: Funktionen für MX Records check
- [x] Backend: Mail Server greift auf eine SQL Datenbank zu mit von Django generierten Daten zu allen E-Mail Usern (oder mit Tabellen Zugriff Beschränkung)
- [x] Lokal: IMAP und SMPT funktionieren mit beliebigem lokalem Client
- [x] Backups funktionieren oder laufen
- [x] Ansible Pipeline
- [ ] Katrin: Datenschutzerklärung updaten

# Rabbit holes

`What could go wrong? Or what problems might come up?`

# No-gos

`What will not be done?`

- Als Alias senden
- Shared Mailbox E-Mail ändern
- Backups pro Postfach herunterladen
- Passwort ändern
- Backups Zugriff für die RLC
- Schutz gegen Brute Force Attacken von außen
- Schutz vor Versenden von Spam von innen
- Verteilerlisten
- Separate Accounts

**Comment by danielmoessner** [comment]
problem: doppelt verwalten der nutzer in der law clinic einmal in law and orga und einmal beim email anbieter
